### ISSUE TITLE
'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by Paranormaly** [naivomah3/lab-cv#1]
I downloaded UDD6 dataset and extracted it in ./input/training and ./input validation
but when I run train I got this error on the first image in 

`data_generator.py", line 25, in get_mask
 mask = mask[:, :, 0]
TypeError: 'NoneType' object is not subscriptable
`

**Comment by naivomah3** [comment]
Hi, thanks for your interest in the project. 

Before I go further, would you show me your `train.sh` config? 
Also the train images and masks(ground-truth) shape along with the ground-truth unique classes. 
I would like to know how you represent the mask matrix values.

**Comment by Paranormaly** [comment]
Thanks for reply first I'm tensorflow newbie.
I'm using the default values in train.sh config. I changed the train/val folders and I had to disable Flops `export GET_FLOPS=False` because it's the only function that not compatible with TF2 (I'm using tensorflow 2 )

Also I didn't use a custom dataset I used the UDD6 as you mentioned it in the notebook to use UDD so I used the latest one
